version: '3.7'

services:

  web_dashboard:
    container_name: remote_presence_dashboard
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000